# -*- mode: ruby -*-
# vi: set ft=ruby :

NODES = {
  'control-plane' => {
    ip: '192.168.56.10',
    cpus: 2,
    memory: 2048
  },
  'worker-1' => {
    ip: '192.168.56.11',
    cpus: 2,
    memory: 2048
  },
  'worker-2' => {
    ip: '192.168.56.12',
    cpus: 2,
    memory: 2048
  }
}

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  NODES.each do |name, cfg|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: cfg[:ip]

      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.cpus = cfg[:cpus]
        vb.memory = cfg[:memory]
      end
    end
  end
end
